// <auto-generated />
using System;
using Jeopareddy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jeopareddy.Api.Data.Migrations
{
    [DbContext(typeof(JeopareddyDbContext))]
    partial class JeopareddyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Jeopareddy.Api.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Clue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GameId", "CategoryId", "RowOrder")
                        .IsUnique();

                    b.ToTable("Clues", t =>
                        {
                            t.HasCheckConstraint("CK_Clue_PointValue_Positive", "PointValue > 0");
                        });
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.ScoreEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClueId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeltaPoints")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClueId");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.ToTable("ScoreEvents");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Category", b =>
                {
                    b.HasOne("Jeopareddy.Api.Domain.Game", "Game")
                        .WithMany("Categories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Clue", b =>
                {
                    b.HasOne("Jeopareddy.Api.Domain.Category", "Category")
                        .WithMany("Clues")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jeopareddy.Api.Domain.Game", "Game")
                        .WithMany("Clues")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.ScoreEvent", b =>
                {
                    b.HasOne("Jeopareddy.Api.Domain.Clue", "Clue")
                        .WithMany("ScoreEvents")
                        .HasForeignKey("ClueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jeopareddy.Api.Domain.Game", "Game")
                        .WithMany("ScoreEvents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jeopareddy.Api.Domain.Team", "Team")
                        .WithMany("ScoreEvents")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clue");

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Team", b =>
                {
                    b.HasOne("Jeopareddy.Api.Domain.Game", "Game")
                        .WithMany("Teams")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Category", b =>
                {
                    b.Navigation("Clues");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Clue", b =>
                {
                    b.Navigation("ScoreEvents");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Game", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Clues");

                    b.Navigation("ScoreEvents");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Jeopareddy.Api.Domain.Team", b =>
                {
                    b.Navigation("ScoreEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
